apiVersion: v1
kind: ServiceAccount
metadata:
  name: sqs-publisher
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::136492549275:role/incident-platform-sqs-publisher-irsa
