apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-service
  namespace: default
  labels:
    app: incident-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incident-service
  template:
    metadata:
      labels:
        app: incident-service
    spec:
      serviceAccountName: incident-service
      containers:
      - name: incident-service
        image: 136492549275.dkr.ecr.us-east-1.amazonaws.com/incident-service:v0.4.0
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: APP_VERSION
          value: "v0.4.0"
        - name: AWS_REGION
          value: "us-east-1"
        - name: SQS_QUEUE_URL
          value: "https://sqs.us-east-1.amazonaws.com/136492549275/incident-platform-alerts"
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: incident-service-secrets
              key: ANTHROPIC_API_KEY
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: incident-service-secrets
              key: SLACK_WEBHOOK_URL
        - name: CLAUDE_MODEL
          value: "claude-haiku-4-5-20251001"
        resources:
          requests:
            memory: "192Mi"
            cpu: "100m"
          limits:
            memory: "384Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 3
          periodSeconds: 5
