apiVersion: v1
kind: Service
metadata:
  name: incident-service
  namespace: default
  labels:
    app: incident-service
    release: kube-prometheus-stack
spec:
  selector:
    app: incident-service
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  type: ClusterIP
